# Generated by Django 2.2.7 on 2020-05-06 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articles',
            options={'verbose_name': 'Статью', 'verbose_name_plural': 'Статьи'},
        ),
    ]
